vich_uploader:
    db_driver: orm

    mappings:
       djibysow:
           uri_prefix: /images/djibysow
           upload_destination: '%kernel.project_dir%/public/images/djibysow'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true