<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxmZ61x\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxmZ61x/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerYxmZ61x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerYxmZ61x\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerYxmZ61x\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'YxmZ61x',
    'container.build_id' => 'f8f63d77',
    'container.build_time' => 1565003115,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxmZ61x');
