<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9tIU1EE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9tIU1EE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9tIU1EE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9tIU1EE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9tIU1EE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9tIU1EE',
    'container.build_id' => '3667e417',
    'container.build_time' => 1565297924,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9tIU1EE');
