<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container95N7uSz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container95N7uSz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container95N7uSz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container95N7uSz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container95N7uSz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '95N7uSz',
    'container.build_id' => '6ceb4f65',
    'container.build_time' => 1565360121,
], __DIR__.\DIRECTORY_SEPARATOR.'Container95N7uSz');
