<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBVvjnWw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBVvjnWw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBVvjnWw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBVvjnWw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBVvjnWw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BVvjnWw',
    'container.build_id' => '42928377',
    'container.build_time' => 1567290247,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBVvjnWw');
